export {
  activeBrand,
  advantages,
  assetsContent,
  automationContent,
  brandContent,
  brandLogos,
  brandSeo,
  brandThemeStyle,
  contactContent,
  contactWindowOptions,
  dealerProfile,
  footerContent,
  formContent,
  heroContent,
  legalContent,
  localeContent,
  processSection,
  processSteps,
  quickContact,
  serviceOptions,
  trustSection,
} from "@/content/brand";

export type {
  AutomationConfig,
  AutomationPayloadKey,
  BrandAssets,
  BrandConfig,
  BrandIdentity,
  ContactContent,
  ContactWindow,
  FormContent,
  LegalContent,
  LocaleConfig,
  ServiceOption,
  ServiceOptionId,
  ServiceKind,
} from "@/content/brand";
